stages :
  - create_docs

create_docs_job:
  stage: create_docs
  variables:
    CI_DEBUG_TRACE: "true"
  allow_failure: true
  image: python:3.7

  before_script:
    - python3 --version
    - pip install virtualenv
    - python3 -m venv challenge_ds
    - source challenge_ds/bin/activate
    - pip --version
    - pip install -r requirements.txt
  script:
    - echo "starting docs generation for python code ... "
    - cd docs
    - sphinx-apidoc -o ./source ../src
    - make html
  only :
    changes :
      - src/*.py
