DATA_DIR: '../data'
OUTPUT_DIR: '../models'
DATASET:
  DATA_FORMAT: csv
  PREPROCESSING:
    NORMALIZE:
      ACTIVE: False
      TYPE: "StandardScaler"  # ["MinMaxScalar", "StandardScaler"]
    PCA:
      ACTIVE: False
      N_COMPONENTS: 0.95
  BATCH_SIZE: 64
  VALID_RATIO: 0.15
  VERBOSITY: True
  NUM_THREADS: 4
MODELS:
  NN: False
  ML:
    ACTIVE: True
    GRID_SEARCH: False
    TYPE: 'ExtraTrees'  # ["RandomForest", "ExtraTrees", "Knn", "NuSVR"]
    RandomForest:
      bootstrap: False
      max_depth: 22
      max_features: 50
      min_samples_split: 4
      n_estimators: 80
      n_jobs: -1
    ExtraTrees:
      bootstrap: False
      max_depth: 20
      max_features: 80
      min_samples_split: 4
      n_estimators: 80
      n_jobs: -1
    Knn:
      n_neighbors: 9
    NuSVR:
      C: 1
      gamma: 'auto'
      kernel: 'rbf'
      nu: 0.5
TRAIN:
  EPOCH: 100
  CHECKPOINT_STEP: 500
  MODEL: LinearNet_1
  LOG_DIR: 'tensorboard/metrics/linear_1'
  SAVE_DIR: '../models'
  LR_INITIAL : 0.001
  LR_DECAY: 0.001
  LR_PATIENCE : 5
  LR_THRESHOLD : 0.01
TEST:
  BATCH_SIZE: 64
  PATH_TO_MODEL: '../models/randomforest_0/model.pck'
  PATH_TO_CSV: './output.csv'
  AVERAGE:
    ACTIVE: True
    PATH:
      - {MODEL: '../models/randomforest_0/model.pck', CONFIG: '../models/randomforest_0/config_file.yaml'}
      - {MODEL: '../models/randomforest_1/model.pck', CONFIG: '../models/randomforest_1/config_file.yaml'}
